TARGET_NAME:=cc2530_local
TARGET_PATH:=${BUILD_DIR_ROOT}/${TARGET_NAME}

.PHONY: ${TARGET_NAME} clean_${TARGET_NAME} upload_${TARGET_NAME}

${TARGET_NAME}: 
	${Q}echo "Building target ${TARGET_NAME}"


clean_${TARGET_NAME}: 
	${Q}echo "Cleaning target ${TARGET_NAME}"


upload_${TARGET_NAME}: ${TARGET_NAME}
	${Q}echo "Uploading target ${TARGET_NAME}"
